# Generated by Django 3.2.12 on 2022-03-28 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
